In [ ]:
# Let printing work the same in Python 2 and 3
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [1]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [2]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)

(3,)
3
1


In [3]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)

(100,)
100
1


In [5]:
y = np.random.rand(5, 80)
# print(y)
print(y.shape)
print(y.size)
print(y.ndim)

(5, 80)
400
2


## Array Manipulation
How to change the shape of an array without a copy!

In [6]:
x.shape = (20, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


NumPy can even automatically figure out the size of at most one dimension for you.

In [7]:
y.shape = (4, 20, -1)
print(y.shape)

(4, 20, 5)


In [8]:
print(y)

[[[5.04990453e-01 1.50213224e-01 7.12300965e-01 2.80148088e-02
   5.96147594e-01]
  [7.64785072e-02 4.09639794e-01 5.67251458e-01 1.17690655e-01
   8.71357530e-01]
  [3.07939995e-01 3.11225559e-02 5.16651843e-01 7.77819255e-01
   3.08783384e-01]
  [7.14952652e-03 9.96520337e-01 5.14230286e-01 9.50977060e-01
   1.64356142e-01]
  [3.62726312e-01 9.23032933e-01 6.26773093e-01 6.32392374e-01
   1.38754838e-01]
  [2.50838884e-01 4.00661137e-01 8.21395413e-01 7.79229622e-01
   6.28271046e-01]
  [7.66712131e-01 9.57541550e-01 7.32142188e-01 6.58358118e-01
   5.11527834e-01]
  [2.42147028e-02 1.63410695e-01 9.13446211e-01 3.49172968e-01
   3.68703388e-01]
  [6.99547088e-01 8.26668894e-01 4.06709571e-01 9.18829174e-01
   9.99298051e-01]
  [9.85295734e-01 5.54258260e-01 2.35769291e-01 3.55320905e-01
   4.04084304e-01]
  [8.50980041e-01 7.34426259e-01 3.54681630e-01 6.16811788e-01
   3.35955272e-01]
  [3.71984098e-01 9.68024771e-01 1.88761673e-01 3.85640887e-02
   8.16496055e-02]
  [3.71471135e-0

## Array Indexing

In [9]:
# Scalar Indexing
print(x[2])

[10 11 12 13 14]


In [10]:
# Slicing
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [12]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [14]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [15]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [10 11 12 13 14]]


## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [16]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (20, 5)
Shape of Y: (4, 20, 5)


Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [18]:
a = x + y
print(a.shape)
b = x[np.newaxis, :, :] + y
print(b.shape)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))

(4, 20, 5)
(4, 20, 5)
(4, 20, 5)
Are a and b identical? True
Are a and c identical? True


In [ ]:
#https://www.geeksforgeeks.org/numpy-tile-python/

In [19]:
# Python Program illustrating
# numpy.tile()

# import numpy as geek

#Working on 1D
arr = np.arange(5)
print("arr : \n", arr)

repetitions = 2
print("Repeating arr 2 times : \n", np.tile(arr, repetitions))

repetitions = 3
print("\nRepeating arr 3 times : \n", np.tile(arr, repetitions))
# [0 1 2 ..., 2 3 4] means [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
# since it was long output, so it uses [ ... ]


arr : 
 [0 1 2 3 4]
Repeating arr 2 times : 
 [0 1 2 3 4 0 1 2 3 4]

Repeating arr 3 times : 
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [20]:
# Python Program illustrating
# numpy.tile()

# import numpy as geek

arr = np.arange(3)
print("arr : \n", arr)

a = 2
b = 2
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

a = 3
b = 2
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

a = 2
b = 3
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)


arr : 
 [0 1 2]

Repeating arr : 
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
arr Shape : 
 (2, 6)

Repeating arr : 
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]
arr Shape : 
 (3, 6)

Repeating arr : 
 [[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]
arr Shape : 
 (2, 9)


In [21]:
# Python Program illustrating
# numpy.tile()

# import numpy as np

arr = np.arange(4).reshape(2, 2)
print("arr : \n", arr)

a = 2
b = 1
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

a = 3
b = 2
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

a = 2
b = 3
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)


arr : 
 [[0 1]
 [2 3]]

Repeating arr : 
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]
arr Shape : 
 (4, 2)

Repeating arr : 
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]
arr Shape : 
 (6, 4)

Repeating arr : 
 [[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]
arr Shape : 
 (4, 6)


Another example of broadcasting two 1-D arrays to make a 2-D array.

In [23]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
print(z.shape)

(100,) (64,)
(64, 100)


In [25]:
print(x[np.newaxis, :].shape)
print(y[:, np.newaxis].shape)


(1, 100)
(64, 1)


In [26]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)

(1, 100) (64, 1)
(64, 100)
